### ISSUE TITLE
Firebase Debug

### ISSUE THREAD

**Issue by Jeiel0rbit** [Irineu333/DatabaseRules#9]
🇧🇷 Informo que está público sua regra no Firebase de "debug". A solução é fazer de alguma forma ocultando isso ou protegendo com a segurança do Google, do contrário, poderá ser alterado ou visto publicamente com dados que não queira compartilhar:

{"development":{"config":"null","config-pt":"null","neo_utils_apps":[{"icon":"https://firebasestorage.googleapis.com/v0/b/fbrules333.appspot.com/o/neo-apps%2Fneo-regex%2Fic_launcher_round.png?alt=media&token=17125faa-db62-4402-862e-2f2987812ccc","name":"Neo Regex","package":"com.neo.regex","url":"null"}],"update_manager":{"download_link":"null","last_version_code":5,"last_version_name":"1.0.4"}},"production":{"config":"https://docs.google.com/document/d/1IcE31FDzZXXWQyUZc6yIfxfxEG0-YzYwbFkaVD_4oPk/edit?usp=sharing","config-pt":"https://docs.google.com/document/d/1Onmfmn1j56gjKYJGL2Hb6B1ZIGDbUTWWQI2JbcTv4Ms/edit?usp=sharing","neo_utils_apps":[{"icon":"https://firebasestorage.googleapis.com/v0/b/fbrules333.appspot.com/o/neo-apps%2Fneo-regex%2Fic_launcher_round.png?alt=media&token=17125faa-db62-4402-862e-2f2987812ccc","name":"Neo Regex","package":"com.neo.regex","url":"https://play.google.com/store/apps/details?id=com.neo.regex"},{"icon":"https://firebasestorage.googleapis.com/v0/b/fbrules333.appspot.com/o/others_apps%2F1652367654238.png?alt=media&token=fd6d6d43-9709-47b4-8d9f-1450704878b5","name":"Setup Rest","package":"com.setuprest.ea","url":"https://play.google.com/store/apps/details?id=com.setuprest.ea"},{"icon":"https://firebasestorage.googleapis.com/v0/b/fbrules333.appspot.com/o/others_apps%2Ficon_setupdev.png?alt=media&token=27a1eba9-3df7-4a71-802d-1fe8c1dd7160","name":"SetupSK","package":"com.SetupSK.AT","url":"https://drive.google.com/file/d/18wAXRXYWhXU4EkZ2xUYu96qJRmpG9PLV/view?usp=drivesdk"}],"update_manager":{"download_link":"https://play.google.com/store/apps/details?id=com.neo.fbrules","last_version_code":5,"last_version_name":"1.0.4"}}}

**Comment by Irineu333** [comment]
@Jeiel17  

Desculpe a demora em responder! Estou ciente que tanto prodution quanto development estão públicos, deixei assim pois não há dados sensíveis, não salvo nada do usuário no banco, servindo apenas para controle de versão e divulgação de outros apps. 

No entanto, não permito a edição. 

Regras
![image](https://user-images.githubusercontent.com/45833588/176757747-27a315d6-1921-4d20-a9bb-c62d37bdd04f.png)

Banco
![image](https://user-images.githubusercontent.com/45833588/176757813-59b7166f-68d9-49d8-96e3-a8936ca2b527.png)

Nesse app o único dado sensível é a PRIVATE KEY do usuário, que é salva criptografada no armazenamento. Talvez você queira dar uma olhada no arquivo CipherUtils.kt, qualquer sugestão de melhoria é bem-vinda!

Obrigado pelo seu tempo!

**Comment by Jeiel0rbit** [comment]
Ah ok, sem problema. Obrigado pela atenção.
